---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: image_gallery
  name: images
  label: images
- type: text
  name: price
  label: price
- type: text
  name: discount_price
  label: discount_price
- type: list
  name: sizes
  label: sizes
- type: list
  name: tags
  label: tags
- type: list
  name: juegos
  label: juegos
pages:
- content/products/anachrony-tokens.md
- content/products/brass-tren-canoa.md
- content/products/dinosaur-island.md
- content/products/maceta-persona-libro.md
- content/products/miniaturas-root.md
- content/products/new-york-zoo-inserto.md
- content/products/protectores-de-fichas.md
- content/products/wingspan-recursos.md
